name: ai_farabi
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  firebase_auth: ^5.5.1
  flutter_polyline_points: ^2.1.0
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.3
  google_maps_flutter: ^2.5.3
  http: ^1.1.0
  get_it: ^8.0.3
  flutter_svg: ^2.0.17
  firebase_core: ^3.11.0
  deepl_dart: ^2.0.0
  geolocator: ^10.1.0
  geolocator_apple: ^2.3.5
  cloud_firestore: ^5.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  url_launcher: ^6.2.5
  flutter_tts: ^4.2.2
  camera: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/map_theme/
