name: jihc_hack
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  json_serializable: ^6.9.3
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  google_maps_flutter: ^2.10.0
  flutter_polyline_points: ^2.1.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8

flutter:
  uses-material-design: true
  assets:
    - assets/astronavt.jpg
